FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /code

COPY requirements/ /code/requirements/

RUN pip install --upgrade pip && pip install -r requirements/dev.txt

COPY manage.py /code/
COPY src/ /code/

CMD ["sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
