repos:
  # github will run `pre-commit run --hook-stage manual -a` and then manually black and flake8
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-yaml
        stages: [ commit, push, manual ]
      - id: check-json
        stages: [ commit, push, manual ]
      - id: end-of-file-fixer
        stages: [ commit, push, manual ]
      - id: trailing-whitespace
        stages: [ commit, push, manual ]
      - id: check-added-large-files
        stages: [ commit, push, manual ]

  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [ python ]
        stages: [ commit, push ]
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [ python ]
        stages: [ commit, push ]
      - id: check_migrations
        name: Check migrations
        language: system
        types: [ python ]
        stages: [ commit, push ]
        entry: python manage.py makemigrations --check
        pass_filenames: false
        always_run: true
      - id: django-auth-test
        name: django-auth-test
        entry: env AUTH_ENABLED=True python manage.py test src.apps.api_auth --settings=src.core.settings.test --parallel
        language: system
        pass_filenames: false
        always_run: true
        stages: [ commit, push ]

      - id: django-apps-test
        name: django-apps-test
        entry: env AUTH_ENABLED=False python manage.py test src --exclude-tag auth --settings=src.core.settings.test --parallel
        language: system
        pass_filenames: false
        always_run: true
        stages: [ commit, push ]
      - id: mypy
        name: mypy
        language: system
        entry: mypy --config-file=mypy.ini
        types: [ python ]
        stages: [ commit, push ]
