import type { ConfigFile } from "@rtk-query/codegen-openapi";

const config: ConfigFile = {
  schemaFile: "http://127.0.0.1:8000/api/schema?format=json",
  apiFile: "./apiTest.ts",
  apiImport: "emptySplitApi",
  outputFile: "./AutoGenerated.ts",
  exportName: "notesApi",
  filterEndpoints: [/.*?notes.*?/],
  hooks: true,
};

export default config;

// use npx @rtk-query/codegen-openapi openApiConfig.cts to run the generation
